"""Initial migration

Revision ID: d5e6e7f12652
Revises: 
Create Date: 2024-10-25 16:03:11.381732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e6e7f12652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=100), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('bleu_score', sa.Float(), nullable=True),
    sa.Column('rouge_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=100), nullable=False),
    sa.Column('average_f1_score', sa.Float(), nullable=True),
    sa.Column('average_bleu_score', sa.Float(), nullable=True),
    sa.Column('average_rouge_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_result')
    op.drop_table('evaluation_result')
    # ### end Alembic commands ###
